// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktpcxnvxqzeygcmaxqje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0cGN4bnZ4cXpleWdjbWF4cWplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMDczMjksImV4cCI6MjA2Mzg4MzMyOX0.tagriWVnLgu5qwD1SIptuo1pQgMux5LkhYDBm8betXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
